### ISSUE TITLE
import error in BattleScribe v2.03.21.166

### ISSUE THREAD

**Issue by matlacki** [Ergofarg/Warhammer-Fantasy-6th-edition#35]
Hi,
I follow the readme.md  with the intent to import the BSI file to the BattleScribe v2.03.21.166 software.  I have pasted "https://github.com/Ergofarg/Warhammer-Fantasy-6th-edition/releases/download/v1.1.1/Warhammer-Fantasy-6th-edition.latest.bsi" into the "Add data -> Add data source -> add Repository source" window, but I am getting an error:

`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 19`

Details:

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 19
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:180)
	at com.google.gson.Gson.fromJson(Gson.java:755)
	at com.google.gson.Gson.fromJson(Gson.java:721)
	at com.google.gson.Gson.fromJson(Gson.java:670)
	at com.google.gson.Gson.fromJson(Gson.java:642)
	at net.battlescribe.a.c.e.d(BattleScribe:463)
	at net.battlescribe.desktop.common.RepositorySourceWindowController.a(BattleScribe:221)
	at net.battlescribe.desktop.common.RepositorySourceWindowController.access$downloadRepositorySource(BattleScribe:22)
	at net.battlescribe.desktop.common.RepositorySourceWindowController$a.a(BattleScribe:247)
	at net.battlescribe.desktop.common.RepositorySourceWindowController$a.call(BattleScribe:245)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

-------------------- Caused By --------------------

java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 19
	at com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:322)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:168)
	at com.google.gson.Gson.fromJson(Gson.java:755)
	at com.google.gson.Gson.fromJson(Gson.java:721)
	at com.google.gson.Gson.fromJson(Gson.java:670)
	at com.google.gson.Gson.fromJson(Gson.java:642)
	at net.battlescribe.a.c.e.d(BattleScribe:463)
	at net.battlescribe.desktop.common.RepositorySourceWindowController.a(BattleScribe:221)
	at net.battlescribe.desktop.common.RepositorySourceWindowController.access$downloadRepositorySource(BattleScribe:22)
	at net.battlescribe.desktop.common.RepositorySourceWindowController$a.a(BattleScribe:247)
	at net.battlescribe.desktop.common.RepositorySourceWindowController$a.call(BattleScribe:245)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

I do not know how to proceed, and if it is an actual error.

**Comment by Ergofarg** [comment]
These messages are for bugs in the coding and not how to get the data installed. Join the Warhammer Fantasy Battle sixth edition facebook group , look in the files section for the current BS update and follow the instructions given within that thread.
